name: Run ndp-min

on:
  schedule:
    - cron: "*/120 * * * *" # Runs every 20 minutes
  workflow_dispatch: # Allows manual run of the workflow

concurrency:
  group: ndp-group
  cancel-in-progress: true

jobs:
  run-ndpm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x" # Use the desired Python version

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Fetch proxies and create proxies.txt
      run: |
        urls=(
          "https://raw.githubusercontent.com/shahid0/super-duper-octo-winner/refs/heads/main/working_proxies.txt"
        )
        > proxies.txt
        for url in "${urls[@]}"; do
          echo "Fetching proxies from $url"
          curl -s $url >> proxies.txt
        done
        echo "Proxies fetched and saved to proxies.txt"

    - name: Create data.txt with secret value
      env:
        DATA_SECRET: ${{ secrets.DATA }}
      run: echo "$DATA_SECRET" > np_tokens.txt

    - name: Run main.py
      run: python3 main.py
