name: Run ndpjs-min

on:
  schedule:
    - cron: "*/20 * * * *" # Runs every 20 minutes
  workflow_dispatch: # Allows manual run of the workflow

concurrency:
  group: ndpjs-group
  cancel-in-progress: true

jobs:
  run-ndpmjs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Using Node.js 18 LTS

    - name: Install dependencies
      run: |
        npm init -y
        npm install axios https-proxy-agent socks-proxy-agent uuid

    - name: Fetch proxies and create proxies.txt
      run: |
        urls=(
          "https://raw.githubusercontent.com/shahid0/super-duper-octo-winner/refs/heads/main/us_working_proxies.txt"
          "https://raw.githubusercontent.com/shahid0/super-duper-octo-winner/refs/heads/main/working_proxies.txt"
        )
        > proxies.txt
        for url in "${urls[@]}"; do
          echo "Fetching proxies from $url"
          curl -s "$url" >> proxies.txt
        done
        echo "Proxies fetched and saved to proxies.txt"
        # Remove empty lines and duplicates
        sed -i '/^[[:space:]]*$/d' proxies.txt
        sort -u proxies.txt -o proxies.txt

    - name: Create np_tokens.txt with secret value
      env:
        DATA_SECRET: ${{ secrets.DATA }}
      run: echo "$DATA_SECRET" > np_tokens.txt

    - name: Run Node.js script
      run: node main.js
      env:
        NODE_NO_WARNINGS: '1' # Suppress deprecation warnings
